spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/st?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: qwe123
server:
  port: 8088
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.lss.st.model